# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


- task: DownloadSecureFile@1
  name: yepublickey
  inputs:
    secureFile: 'sshfile.pub'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$( client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(yepublickey.secureFilePath)'
    backendType: 'azurerm'
    backendServiceArm: 'azuree'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'backendkaresource'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'backendstorageshreeramji'
    backendAzureRmContainerName: 'backendcontainrshreeramji'
    backendAzureRmKey: 'keybackendkliye'
    allowTelemetryCollection: true
